
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_FAIL = "DELETE_FROM_CART_FAIL";

export const DELETE_ALL_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_ALL_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_ALL_FROM_CART_FAIL = "DELETE_FROM_CART_FAIL";

export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL";


